global:
 scrape_interval: 1m

scrape_configs:
  - job_name: redis
    static_configs:
      - targets:
        - 192.168.0.201:9121
  - job_name: kafka
    static_configs:
      - targets:
        - kafka-exporter:9308
  - job_name: postgres
    static_configs:
      - targets:
        - postgres-exporter:9187
  - job_name: sentry-node
    static_configs:
      - targets:
        - node-exporter:9100
  - job_name: redis-node
    static_configs:
      - targets:
        - 192.168.0.201:9100
