global:
 scrape_interval: 1m

scrape_configs:
  - job_name: redis
    static_configs:
      - targets:
        - 192.168.0.201:9121
  - job_name: kafka
    static_configs:
      - targets:
        - kafka-exporter:9308
  - job_name: postgres
    static_configs:
      - targets:
        - 192.168.0.202:9187
